name: Validate schema

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Validate JSON Schema
      uses: walbo/validate-json@v1.1.0
      with:
        # Files to validate
        files: schemas/base.json
        # Choose schema version
        schema-version: draft-07
